# stages:
#   - clear
#   - deploy

# docker-build:
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE =~ /deploy$/'
#       when: always
#   stage: clear
#   script:
#     - docker --version 
#     - echo "Removing any pre-existing containers and their volumes which may already exist..."
#     - docker-compose rm -f -s -v 
#     - echo "Removing any images related to docker compose file..."
#     - docker-compose down --rmi all 
# docker-deploy:
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE =~ /deploy$/'
#       when: always
#   stage: deploy
#   script:
#     - docker-compose up -d --force-recreate 



# k3s-build:
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#   stage: clear
#   script:
#     - echo "bulding the image"
#     - docker build -t registry.nated.io/phosphorusmyesophagus/natedresume .
#     - docker push registry.nated.io/phosphorusmyesophagus/natedresume

# k3s-deploy:
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#   stage: clear
#   script:
#     - echo "deploy manifest file"
#     - kubectl apply -f deploy.yaml
