---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: natedca-ingress
spec:
  rules:

  - host: nated.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: natedca-svc
            port:
              number: 8080
        
  - host: www.nated.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: natedca-svc
            port:
              number: 8080
              
  tls:
  - hosts:
    - nated.ca
    - www.nated.ca
    secretName: natedca
---
apiVersion: v1
kind: Service
metadata:
  name: natedca-svc
  labels:
    app: natedca
spec:
  selector:
    app: natedca
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: natedca-depl
spec:
  replicas: 10
  selector:
    matchLabels:
      app: natedca
  template:
    metadata:
      labels:
        app: natedca
    spec:
      imagePullSecrets:
      - name: registry.nated.io
      containers:
      - name: natedca
        image: registry.nated.io/phosphorusmyesophagus/natedresume:latest
        ports:
          - containerPort: 8080
            hostPort: 8080
