---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: natedio
spec:
  tls:
    - hosts:
        - nated.io
      secretName: natedio
  rules:
    - host: nated.io
      http:
        paths:
          - path: /
            backend:
              serviceName: natedio
              servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: natedio
spec:
  type: ClusterIP
  selector:
    app: natedio
  ports:
    - protocol: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: natedio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: natedio
  template:
    metadata:
      labels:
        app: natedio
    spec:
      containers:
        - name: natedio
          image: registry.nated.io/phosphorusmyesophagus/natedresume:latest
          ports:
            - containerPort: 8080
      imagePullSecret:
      - name: natedio-registry
