---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: natedca
spec:
  rules:
  - host: nated.ca
    http:
      paths:
      - backend:
          service:
            name: natedca
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - nated.ca
    secretName: natedca
---
apiVersion: v1
kind: Service
metadata:
  name: natedca
spec:
  ports:
  - port: 8080
  selector:
    app: natedca
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: natedca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: natedca
  template:
    metadata:
      labels:
        app: natedca
    spec:
      containers:
      - image: container-image
        imagePullPolicy: Always
        name: natedca
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: 500Mi
          requests:
            cpu: "0.25"
            memory: 200Mi
      imagePullSecrets:
      - name: ghcr.io-secret
