apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: natedca
spec:
  rules:
  - host: nated.ca
    http:
      paths:
      - backend:
          service:
            name: natedca
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - nated.ca
    secretName: natedca

---
apiVersion: v1
kind: Service
metadata:
  name: natedca
spec:
  type: ClusterIP
  selector:
    app: natedca
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: natedca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: natedca
  template:
    metadata:
      labels:
        app: natedca
    spec:
      containers:
        - name: natedca
          image: ghcr.io/delduked/natedresume:v_4f85ab6
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
            requests:
              cpu: "0.25"
              memory: "200Mi"
      imagePullSecrets:
        - name: ghcr.io-secret

