name: TagReleaseBuildPushDeploy
on:
  push:
    branches:
      - civo

jobs:
  setup:
    runs-on: [self-hosted, Linux, X64, natedresume]
    outputs:
      tagname: ${{ steps.create_tag.outputs.tagname }}
      tag: ${{ steps.create_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Calculate next release tag
        id: create_tag
        run: |
          VERSION=$(git rev-parse --short HEAD)
          DATE=$(date +'%Y%m%d')
          VVERSION=${DATE}v_${VERSION}
          echo "tag=v_${VERSION}" >> $GITHUB_OUTPUT
          echo "tagname=${VVERSION}" >> $GITHUB_OUTPUT

      - name: Build and push docker image
        id: docker_build
        run : |
          echo "building natedresume image"
          export CR_PAT=${{ secrets.GH_RUNNER }} ; echo $CR_PAT | docker login ghcr.io -u delduked --password-stdin
          docker build -t ghcr.io/delduked/natedresume:${{ steps.create_tag.outputs.tag }} ./ -f ./nated.dockerfile
          docker push ghcr.io/delduked/natedresume:${{ steps.create_tag.outputs.tag }} 
          echo "image natedresume was built and pushed succesfully."
  kubectl:
    needs: setup
    runs-on: [self-hosted, Linux, X64, natedresume]
    steps:
      
      - uses: actions/checkout@v3

      - name: kubectl
        id: kubectl
        run: |
          echo "${{ secrets.CIVO_KUBE_CONFIG }}" > /home/gh/.kube/config
          kubectl config set-context nated-cluster

          # Hardcoded values
          manifest_file="./natedresume.yaml"  # Replace with your actual file path

          # Check if the manifest file exists
          if [ ! -f "$manifest_file" ]; then
              echo "Error: Manifest file does not exist."
              exit 1
          fi

          # Use sed to replace the image tag
          sed -i "s|container-image|ghcr.io/delduked/natedresume:${{ steps.create_tag.outputs.tag }}|g" $manifest_file >> deploy.yaml
          echo "version: ${{ steps.create_tag.outputs.tag }}"
          echo "Image tag updated in manifest file."
          cat deploy.yaml
          kubectl apply -f deploy.yaml --namespace natedca

        shell: bash

  release:
    needs: kubectl
    runs-on: [self-hosted, Linux, X64, natedresume]
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RUNNER }}
        with:
          tag_name: ${{ needs.setup.outputs.tag }}
          release_name: ${{ needs.setup.outputs.tagname }}
          draft: false
          prerelease: false